//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public Bolum()
        {
            this.Ogrencis = new HashSet<Ogrenci>();
        }
    
        public int bolumID { get; set; }
        public string bolum1 { get; set; }
        public Nullable<int> fakulteID { get; set; }
    
        public virtual Fakulte Fakulte { get; set; }
        public virtual ICollection<Ogrenci> Ogrencis { get; set; }
    }
}
