//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fakulte
    {
        public Fakulte()
        {
            this.Bolums = new HashSet<Bolum>();
        }
    
        public int fakulteID { get; set; }
        public string fakulte1 { get; set; }
    
        public virtual ICollection<Bolum> Bolums { get; set; }
    }
}
