//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KutuphaneBolum
    {
        public KutuphaneBolum()
        {
            this.Personels = new HashSet<Personel>();
        }
    
        public int kutuphanebolumID { get; set; }
        public string kutuphanebolum1 { get; set; }
    
        public virtual ICollection<Personel> Personels { get; set; }
    }
}
