//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenci
    {
        public int ogrenciID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public Nullable<int> bolumID { get; set; }
        public Nullable<System.DateTime> kayitYili { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<bool> mevzun { get; set; }
        public Nullable<System.DateTime> mevzuniyet_tarihi { get; set; }
    
        public virtual Bolum Bolum { get; set; }
    }
}
