//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personel
    {
        public Personel()
        {
            this.Rapors = new HashSet<Rapor>();
        }
    
        public int personelID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string kullaniciadi { get; set; }
        public string sifre { get; set; }
        public Nullable<int> kutuphanebolumID { get; set; }
        public Nullable<bool> yetki { get; set; }
    
        public virtual KutuphaneBolum KutuphaneBolum { get; set; }
        public virtual ICollection<Rapor> Rapors { get; set; }
    }
}
