//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rapor
    {
        public int raporID { get; set; }
        public string gerekce { get; set; }
        public Nullable<int> personelID { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
        public string konu { get; set; }
    
        public virtual Personel Personel { get; set; }
    }
}
