//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class YayinEvi
    {
        public YayinEvi()
        {
            this.Yazars = new HashSet<Yazar>();
        }
    
        public int yayineviID { get; set; }
        public string yayinevi_ad { get; set; }
        public Nullable<System.DateTime> kurulus { get; set; }
    
        public virtual ICollection<Yazar> Yazars { get; set; }
    }
}
