//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kutuphane.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yazar
    {
        public Yazar()
        {
            this.Kitaps = new HashSet<Kitap>();
        }
    
        public int yazarID { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string telefon { get; set; }
        public Nullable<int> yas { get; set; }
        public Nullable<int> yayineviID { get; set; }
    
        public virtual ICollection<Kitap> Kitaps { get; set; }
        public virtual YayinEvi YayinEvi { get; set; }
    }
}
